### ISSUE TITLE
It does not run on Ubuntu-20.04 by missing libraries

### ISSUE THREAD

**Issue by CazYokoyama** [i-nod/system-config-lvm#1]
system-config-lvm fails by the following error.

$ sudo ./src/system-config-lvm
Traceback (most recent call last):
  File "./src/system-config-lvm", line 171, in <module>
    runFullGUI()
  File "./src/system-config-lvm", line 152, in runFullGUI
    glade_xml = initGlade()
  File "./src/system-config-lvm", line 148, in initGlade
    glade_xml.add_from_file(gladepath)
gi.repository.GLib.Error: gtk-builder-error-quark: /usr/share/system-config-lvm//lvui.glade:5:1 Unhandled tag: <glade-interface> (1)

Before above run, I run
./configure 
make

Even I install
sudo apt install -y intltool libglade2-dev glade libgladeui-dev python3-pip

The execution has no change.

**Comment by i-nod** [comment]
I haven't tested on ubuntu 20.04 but I will take a look.  glade isn't a problem here though since it no longer uses glade but instead used gtk builder.  This is clearly a difference in gtk versions based on the unhandled tag error.  I will see if I can figure out which tag in the lvui.glade file it doesn't like, there is probably one that has been deprecated.

**Comment by i-nod** [comment]
I managed to get it to run after making a small change to utilities.py for the location of the readlink directory.  In running the build scripts on ubuntu I noticed the make install didn't seem to create the appropriate paths which lead to me having to manually create folders and install files.  I suspect /usr/share/system-config-lvm//lvui.glade is from a different version of system-config-lvm and not from the git repository.  You should remove all items from /usr/share/system-config-lvm and use the ones provided in the repository.  The instructions to manually install are as follows. (note: it will still not be able to initialize a pv until I fix the readlink change so I would recommend fetching the latest after I commit this fix)
1. run the configure script
2. run the make / make install
3. sudo mkdir -p /usr/share/system-config-lvm/
from inside the git folder:
4. sudo cp -a src/* /usr/share/system-config-lvm/

This will make sure its using the updated glade files (now in gtk builder format and not the old incompatible glade format)

**Comment by i-nod** [comment]
Additionally here is a screenshot of it running
![Screenshot from 2022-01-09 21-38-53](https://user-images.githubusercontent.com/95187090/148723312-b1086e0b-cef1-481d-a7c3-7785ead1104d.png)

**Comment by i-nod** [comment]
updated the release with the small fix I made for ubuntu. If you can confirm this works I will close this issue.

**Comment by CazYokoyama** [comment]
I confirm above instruction with the commit, d77f42eda5fed1115d9a4512c502e061e1988219 works fine. Thank you.
It seems your code expects src/* in /usr/share/system-config-lvm/ while "make install" does

sudo mkdir -p /usr/**local**/share/system-config-lvm/
sudo cp -a src/* /usr/**local**/share/system-config-lvm/

Could you update your code for "sudo make install" and make sure we don't need to copy src/*?

As you know, changing /usr/**local**/ to /usr/ is done by an option of configure.

**Comment by i-nod** [comment]
OK that makes sense, I suspect what is happening is that the configure script is not updating the location the python files use to look for their local files.  If you ran ./configure --prefix=/usr you wouldn't have noticed an issue.  The real fix is probably to have configure make a python file containing the prefix that can be imported for finding the assets and xml files and then have the python files change to use this for their file locations.  I will see what I can do but in the mean time will close this issue.
